FORMAT: 1A
HOST: https://my-joolz.nl/wp-json/configurator-api/v1

# Joolz Configurator

API to retrieve WooCommerce data for the new configurator.

Host is based on for which country this configurator will be. For example, the API for the German shop will be available at https://my-joolz.de/wp-json/configurator-api/v1

## Error response

In case of an error, all endpoints will return this JSON object. The code and message will be different for each type of error.

### Error response example

+ Response (application/json)

        {
            "code": "not_found",
            "message": "Product not found.",
            "data": {
                "status": 404
            }
        }

## Info [/info]

### Get shop info [GET]

Retrieve basic info for current shop.

+ Response 200 (application/json)

        {
            "locale": "nl_NL",
            "currency": "EUR"
        }

## Cart [/cart/add]

### Add to cart [POST]

Add given product(s) and/or variation(s) with given identifier(s) to the cart. 
For the My Joolz Bumper Bar you can pass the bar text using the meta property.
The number of items succesfully added to the cart will be returned.

+ Request (application/json)

        {
            "products": [
                {
                    "identifier": "897232"
                },
                {
                    "identifier": "192312"
                    "meta": {
                        "custom_text": "MY TEXT"
                    }
                },
                {
                    "identifier": "697212"
                }
            ]
        }

+ Response 200 (application/json)

        {
            "count": 3
        }
        
## Wishlist [/wishlist/add]

### Add to wishlist [POST]

Add given product(s) and/or variation(s) with given identifier(s) to the wishlist. 
The number of items succesfully added to the wishlist will be returned.

+ Request (application/json)

        {
            "identifiers": [
                "897232",
                "192312",
                "697212"
            ]
        }

+ Response 200 (application/json)

        {
            "count": 3
        }

## Models [/models]

### List All Models [GET]

Retrieve all available models and products.

#### Please note: The Joolz Day³ Tailor only returns 4 values for the 'Accent' attribute in the example response. In reality there are 20.

+ Response 200 (application/json)

        [
            {
                "identifier": "hub",
                "label": "Hub",
                "description": "urban | compact",
                "features": [
                    "doorkijkventilatie in de wieg & hoofdkussen in matras",
                    "soepele vering",
                    "hoge wieg en stoel",
                    "verstelbare voetsteun & gordel",
                    "compacte inklapmogelijkheid",
                    "staand opbergen"
                ],
                "products": [
                    {
                        "identifier": "hub-looks",
                        "name": "Joolz Hub",
                        "customize": 0,
                        "default": 1,
                        "attributes": [
                            {
                                "identifier": "fabric",
                                "external_identifier": "Main_Color_Collection",
                                "label": "Bekleding",
                                "values": [
                                    {
                                        "identifier": "parrot-blue",
                                        "external_identifier": "main_ParrotBlue",
                                        "label": "Parrot Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Parrot-blue-80.png"
                                    },
                                    {
                                        "identifier": "hippo-grey",
                                        "external_identifier": "main_HippoGrey",
                                        "label": "Hippy Grey",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Hippo-grey-80.png"
                                    },
                                    {
                                        "identifier": "nero",
                                        "external_identifier": "main_Nero",
                                        "label": "Nero",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "identifier": "day3",
                "label": "Day³",
                "description": "something | else",
                "features": [
                    "doorkijkventilatie in de wieg & hoofdkussen in matras",
                    "soepele vering",
                    "hoge wieg en stoel",
                    "verstelbare voetsteun & gordel",
                    "compacte inklapmogelijkheid",
                    "staand opbergen"
                ],
                "products": [
                    {
                        "identifier": "day3-looks",
                        "name": "Joolz Day³ Looks",
                        "customize": 0,
                        "default": 1,
                        "attributes": [
                            {
                                "identifier": "fabric",
                                "external_identifier": "Main_Color_Collection",
                                "label": "Bekleding",
                                "values": [
                                    {
                                        "identifier": "parrot-blue",
                                        "external_identifier": "main_ParrotBlue",
                                        "label": "Parrot Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Parrot-blue.png"
                                    },
                                    {
                                        "identifier": "hippo-grey",
                                        "external_identifier": "main_HippoGrey",
                                        "label": "Hippy Grey",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Hippo-Grey.png"
                                    },
                                    {
                                        "identifier": "elephant-grey",
                                        "external_identifier": "main_elephantGrey",
                                        "label": "Elephant Grey",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Elephant-grey.png"
                                    },
                                    {
                                        "identifier": "camel-beige",
                                        "external_identifier": "main_CamelBeige",
                                        "label": "Camel Beige",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Camel-beige-1-1.png"
                                    },
                                    {
                                        "identifier": "amazing-grey",
                                        "external_identifier": "main_AmazingGrey",
                                        "label": "Amazing Grey",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Amazing-grey-80.png"
                                    },
                                    {
                                        "identifier": "graphite-grey",
                                        "external_identifier": "main_GraphiteGrey",
                                        "label": "Graphite Grey",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Graphite-grey-80.png"
                                    },
                                    {
                                        "identifier": "midnight-blue",
                                        "external_identifier": "main_MidnightBlue",
                                        "label": "Midnight Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Midnight-Blue-80-1.png"
                                    },
                                    {
                                        "identifier": "grigio-nuovo",
                                        "external_identifier": "main_GrigioNuovo",
                                        "label": "Grigio Nuovo",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Grigio-nuovo-80.png"
                                    },
                                    {
                                        "identifier": "nero",
                                        "external_identifier": "main_Nero",
                                        "label": "Nero",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "identifier": "day3-tailor",
                        "name": "Joolz Day³ Tailor",
                        "customize": 1,
                        "default": 0,
                        "attributes": [
                            {
                                "identifier": "fabric",
                                "external_identifier": "Main_Color_Collection",
                                "label": "Bekleding",
                                "values": [
                                    {
                                        "identifier": "grey",
                                        "external_identifier": "main_Grey",
                                        "label": "Grey",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Fabric-0001-Grey-2.png"
                                    },
                                    {
                                        "identifier": "black",
                                        "external_identifier": "main_Black",
                                        "label": "Black",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Fabric-0003-Black-2.png"
                                    },
                                    {
                                        "identifier": "silver",
                                        "external_identifier": "main_Silver",
                                        "label": "Silver",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Fabric-0003-Silver-2.png"
                                    }
                                ]
                            },
                            {
                                "identifier": "chassis",
                                "external_identifier": "Main_Color_Chassis",
                                "label": "Chassis",
                                "values": [
                                    {
                                        "identifier": "black",
                                        "external_identifier": "chassis_Black",
                                        "label": "Black",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Chassis-0002-Black-2.png"
                                    },
                                    {
                                        "identifier": "silver",
                                        "external_identifier": "chassis_Silver",
                                        "label": "Silver",
                                        "default": 1,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Chassis-0001-Silver-2.png"
                                    }
                                ]
                            },
                            {
                                "identifier": "wheel-color",
                                "external_identifier": "Main_Color_Wheels",
                                "label": "Wielen",
                                "values": [
                                    {
                                        "identifier": "black",
                                        "external_identifier": "wheels_Black",
                                        "label": "Black",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Wheels-Black-2.png"
                                    },
                                    {
                                        "identifier": "silver",
                                        "external_identifier": "wheels_Silver",
                                        "label": "Silver",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Wheels-Silver-2.png"
                                    }
                                ]
                            },
                            {
                                "identifier": "accent",
                                "label": "Accent",
                                "external_identifier": "Main_Color_Accents",
                                "values": [
                                    {
                                        "identifier": "angel-blue",
                                        "external_identifier": "accents_AngelBlue",
                                        "label": "Angel Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00000-Angel-blue-1.png"
                                    },
                                    {
                                        "identifier": "emerald-green",
                                        "external_identifier": "accents_EmeraldGreen",
                                        "label": "Emerald Green",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00013-Emerald-green-1.png"
                                    },
                                    {
                                        "identifier": "tango-red",
                                        "external_identifier": "accents_TangoRed",
                                        "label": "Tango Red",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00020-Tango-red-2.png"
                                    },
                                    {
                                        "identifier": "tangerine-tango",
                                        "external_identifier": "accents_TangerineTango",
                                        "label": "Tangerine Tango",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00019-Tangerine-tango-2.png"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
        
## Products [/products/{identifier}]

### Get product [GET]

Retrieve a product by identifier. Only works for products without attributes and variations.

+ Parameters

    + identifier - The unqiue product identifier

+ Response 200 (application/json)

        {
            "id": 67711,
            "name": "Joolz Cup Holder",
            "price": 39,
            "tax_label": " (incl. BTW)",
            "sku": "500199",
            "ean": "XXXXXXXXXXXX",
            "image": "https://my-joolz.nl/url-to-image.jpg",
            "cart_link": "/cart/?configurator=true&add-to-cart=67711&user-hash=xxx",
            "in_stock": 1,
            "stock_status": "In stock: Delivery within 5 working days",
            "text_color": ""
        }

## Product Variations [/products/{identifier}/variations/{attributes}]

### Get variation [GET]

Retrieve a variation by product identifier and attribute values.
The text_color property will contain 'white' or 'black' in case
of a My Joolz Bumper Bar variation.

+ Parameters

    + identifier - The unqiue product identifier
    + attributes - The attributes of the variation.<br/>Format: attribute-identifier:value-identifier,attribute-identiefer:value-identifier<br/>Example: fabric:black,chassis:silver,wheel-color:black,accent:emerald-green

+ Response 200 (application/json)

        {
            "id": 67755,
            "name": "Joolz Day³ Tailor Bekleding: Black, Chassis: Silver, Wielen: Black, Accent: Emerald Green",
            "price": 1099,
            "tax_label": " (incl. BTW)",
            "sku": "500099",
            "ean": "XXXXXXXXXXXX",
            "image": "https://my-joolz.nl/url-to-image.jpg",
            "cart_link": "/cart/?configurator=true&add-to-cart=67755&user-hash=xxx",
            "in_stock": 1,
            "stock_status": "In stock: Delivery within 2 weeks",
            "text_color": ""
        }
        
## Accessories [/models/{identifier}/accessories]

### List available accessories [GET]

To retrieve all available accessories for given model.

+ Parameters

    + identifier - The unique identifier of the model
    
+ Response 200 (application/json)

        {
            "accessories": [
                {
                    "identifier": 432432,
                    "external_identifier": "Accessory - Cupholder",
                    "name": "Joolz Bekerhouder",
                    "description": "Something about the Joolz Bekerhouder",
                    "features": "<strong>+ </strong>morst niet<strong>+ </strong>perfect voor flesjes &amp; tuitbekers<strong>+ </strong>geschikt voor de Joolz Hub, Day<span>², </span>Joolz Geo &amp; Joolz Geo²",
                    "sku": "50121",
                    "price": 29.95,
                    "tax_label": " (incl. BTW)",
                    "attributes": [],
                    "cart_link": "/cart/?configurator=true&add-to-cart=1234&user-hash=xxx"
                    "image": "https://my-joolz.nl/url-to-image.jpg",
                    "should_match_stroller": 0,
                    "in_stock": 0,
                    "stock_status": "Out of stock: Expected on [DATE]",
                    "text_input_allowed": 0
                },
                {
                    "identifier": 34534,
                    "external_identifier": "Accessory - Footmuff",
                    "name": "Joolz Slaapzak",
                    "description": "Something about the Joolz Slaapzak",
                    "features": "<strong>+ </strong>morst niet<strong>+ </strong>perfect voor flesjes &amp; tuitbekers<strong>+ </strong>geschikt voor de Joolz Hub, Day<span>², </span>Joolz Geo &amp; Joolz Geo²",
                    "sku": "",
                    "price": 0,
                    "tax_label": " (incl. BTW)",
                    "attributes": [
                        {
                            "identifier": "fabric",
                            "external_identifier": "Accessory Color - Footmuff",
                            "label": "Bekleding",
                            "values": [
                                {
                                    "identifier": "parrot-blue",
                                    "external_identifier": "footmuff_ParrotBlue",
                                    "label": "Parrot Blue",
                                    "default": 0,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Parrot-blue-80.png"
                                },
                                {
                                    "identifier": "hippo-grey",
                                    "external_identifier": "footmuff_HippoGrey",
                                    "label": "Hippy Grey",
                                    "default": 1,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Hippo-grey-80.png"
                                },
                                {
                                    "identifier": "nero",
                                    "external_identifier": "footmuff_Nero",
                                    "label": "Nero",
                                    "default": 0,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                }
                            ]
                        }
                    ],
                    "cart_link": "",
                    "image": "",
                    "should_match_stroller": 1,
                    "in_stock": 1,
                    "stock_status": "In stock: Delivery within 5 working days",
                    "text_input_allowed": 0
                }
                
            ]
        }
        
## Configuration accessories [/models/{identifier}/configuration-accessories]

### List available configuration accessories [GET]

To retrieve all available configuration accessories for given model. These are 'highlighted' accessories like the Expandable set for Geo and the Cocoon for Hub.

+ Parameters

    + identifier - The unique identifier of the model
    
+ Response 200 (application/json)

        {
            "accessories": [
                {
                    "identifier": 1234,
                    "external_identifier": "ExpandableSet",
                    "name": "Joolz Uitbreidingsset",
                    "description": "Something about the Joolz Uitbreidingsset",
                    "features": "<strong>+ </strong>morst niet<strong>+ </strong>perfect voor flesjes &amp; tuitbekers<strong>+ </strong>geschikt voor de Joolz Hub, Day<span>², </span>Joolz Geo &amp; Joolz Geo²",
                    "sku": "50111",
                    "price": 99.95,
                    "tax_label": " (incl. BTW)",
                    "attributes": [],
                    "cart_link": "/cart/?configurator=true&add-to-cart=1234&user-hash=xxx"
                    "image": "https://my-joolz.nl/url-to-image.jpg",
                    "should_match_stroller": 1,
                    "in_stock": 0,
                    "stock_status": "Out of stock: Expected on [DATE]"
                },
                {
                    "identifier": 3121,
                    "external_identifier": "Joolz Hub Cocoon",
                    "name": "Joolz Hub Cocoon",
                    "description": "Something about the Joolz Hub Cocoon",
                    "features": "<strong>+ </strong>morst niet<strong>+ </strong>perfect voor flesjes &amp; tuitbekers<strong>+ </strong>geschikt voor de Joolz Hub, Day<span>², </span>Joolz Geo &amp; Joolz Geo²",
                    "sku": "",
                    "price": 0,
                    "tax_label": " (incl. BTW)",
                    "attributes": [
                        {
                            "identifier": "fabric",
                            "external_identifier": "Accessory Color - Footmuff",
                            "label": "Bekleding",
                            "values": [
                                {
                                    "identifier": "parrot-blue",
                                    "external_identifier": "footmuff_ParrotBlue",
                                    "label": "Parrot Blue",
                                    "default": 0,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Parrot-blue-80.png"
                                },
                                {
                                    "identifier": "hippo-grey",
                                    "external_identifier": "footmuff_HippoGrey",
                                    "label": "Hippy Grey",
                                    "default": 1,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Hippo-grey-80.png"
                                },
                                {
                                    "identifier": "nero",
                                    "external_identifier": "footmuff_Nero",
                                    "label": "Nero",
                                    "default": 0,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                }
                            ]
                        }
                    ],
                    "cart_link": "",
                    "image": "",
                    "should_match_stroller": 1,
                    "in_stock": 1,
                    "stock_status": "In stock: Delivery within 5 working days"
                }
                
            ]
        }