FORMAT: 1A
HOST: https://my-joolz.nl/wp-json/configurator-api/v1

# Joolz Configurator

API to retrieve WooCommerce data for the new configurator.

Host is based on for which country this configurator will be.

## Models [/models]

### List All Models [GET]

Retrieve all available models and products.

#### Please note: The Joolz Day³ Tailor only returns 4 values for the 'Accent' attribute in the example response. In reality there are 20.

+ Response 200 (application/json)

        [
            {
                "id": 4,
                "label": "Hub",
                "description": "Something about the Hub",
                "products": [
                    {
                        "identifier": "hub-looks",
                        "name": "Joolz Hub",
                        "description": "Something about the Hub looks",
                        "customize": 0,
                        "default": 1,
                        "attributes": [
                            {
                                "identifier": "fabric",
                                "label": "Bekleding",
                                "values": [
                                    {
                                        "identifier": "parrot-blue",
                                        "label": "Parrot Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Parrot-blue-80.png"
                                    },
                                    {
                                        "identifier": "hippo-grey",
                                        "label": "Hippy Grey",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Hippo-grey-80.png"
                                    },
                                    {
                                        "identifier": "nero",
                                        "label": "Nero",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "id": 1,
                "label": "Day³",
                "description": "Something about the Day³",
                "products": [
                    {
                        "identifier": "day3-looks",
                        "name": "Joolz Day³ Looks",    
                        "description": "Something about the Day³ looks",
                        "customize": 0,
                        "default": 1,
                        "attributes": [
                            {
                                "identifier": "fabric",
                                "label": "Bekleding",
                                "values": [
                                    {
                                        "identifier": "parrot-blue",
                                        "label": "Parrot Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Parrot-blue.png"
                                    },
                                    {
                                        "identifier": "hippo-grey",
                                        "label": "Hippy Grey",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Hippo-Grey.png"
                                    },
                                    {
                                        "identifier": "elephant-grey",
                                        "label": "Elephant Grey",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Elephant-grey.png"
                                    },
                                    {
                                        "identifier": "camel-beige",
                                        "label": "Camel Beige",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Day3-Attribute-Earth-Camel-beige-1-1.png"
                                    },
                                    {
                                        "identifier": "amazing-grey",
                                        "label": "Amazing Grey",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Amazing-grey-80.png"
                                    },
                                    {
                                        "identifier": "graphite-grey",
                                        "label": "Graphite Grey",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Graphite-grey-80.png"
                                    },
                                    {
                                        "identifier": "midnight-blue",
                                        "label": "Midnight Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Midnight-Blue-80-1.png"
                                    },
                                    {
                                        "identifier": "grigio-nuovo",
                                        "label": "Grigio Nuovo",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Grigio-nuovo-80.png"
                                    },
                                    {
                                        "identifier": "nero",
                                        "label": "Nero",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "identifier": "day3-tailor",
                        "name": "Joolz Day³ Tailor",
                        "description": "Something about the Day³ tailor",
                        "customize": 1,
                        "default": 0,
                        "attributes": [
                            {
                                "identifier": "fabric",
                                "label": "Bekleding",
                                "values": [
                                    {
                                        "identifier": "grey",
                                        "label": "Grey",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Fabric-0001-Grey-2.png"
                                    },
                                    {
                                        "identifier": "black",
                                        "label": "Black",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Fabric-0003-Black-2.png"
                                    },
                                    {
                                        "identifier": "silver",
                                        "label": "Silver",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Fabric-0003-Silver-2.png"
                                    }
                                ]
                            },
                            {
                                "identifier": "chassis",
                                "label": "Chassis",
                                "values": [
                                    {
                                        "identifier": "black",
                                        "label": "Black",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Chassis-0002-Black-2.png"
                                    },
                                    {
                                        "identifier": "silver",
                                        "label": "Silver",
                                        "default": 1,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Chassis-0001-Silver-2.png"
                                    }
                                ]
                            },
                            {
                                "identifier": "wheel-color",
                                "label": "Wielen",
                                "values": [
                                    {
                                        "identifier": "black",
                                        "label": "Black",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Wheels-Black-2.png"
                                    },
                                    {
                                        "identifier": "silver",
                                        "label": "Silver",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Wheels-Silver-2.png"
                                    }
                                ]
                            },
                            {
                                "identifier": "accent",
                                "label": "Accent",
                                "values": [
                                    {
                                        "identifier": "angel-blue",
                                        "label": "Angel Blue",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00000-Angel-blue-1.png"
                                    },
                                    {
                                        "identifier": "emerald-green",
                                        "label": "Emerald Green",
                                        "default": 1,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00013-Emerald-green-1.png"
                                    },
                                    {
                                        "identifier": "tango-red",
                                        "label": "Tango Red",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00020-Tango-red-2.png"
                                    },
                                    {
                                        "identifier": "tangerine-tango",
                                        "label": "Tangerine Tango",
                                        "default": 0,
                                        "new": 0,
                                        "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Attribute-Collections-Website-Pushchairs-00019-Tangerine-tango-2.png"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]

## Variations [/products/{identifier}/variations/{attributes}]

### Get variation [GET]

Retrieve a variation by attribute values.

+ Parameters

    + identifier - The unqiue product identifier
    + attributes - The attributes of the variation.<br/>Format: attribute-identifier:value-identifier,attribute-identiefer:value-identifier<br/>Example: fabric:black,chassis:silver,wheel-color:black,accent:emerald-green

+ Response 200 (application/json)

        {
            "id": 67755,
            "name": "Joolz Day³ Tailor Bekleding: Black, Chassis: Silver, Wielen: Black, Accent: Emerald Green",
            "price": 1099,
            "sku": "500099",
            "ean": "XXXXXXXXXXXX",
            "cart_link": "/cart/?configurator=true&add-to-cart=67755&user-hash=xxx",
            "in_stock": 1
        }
        
## Accessories [/models/{id}/accessories]

### List available accessories [GET]

To retrieve all available accessories.
Retrieving the accessories requires 
the model ID.

+ Parameters

    + id - The ID of the model
    
+ Response 200 (application/json)

        {
            "accessories": [
                {
                    "identifier": "joolz-cupholder",
                    "name": "Joolz Bekerhouder",
                    "description": "Something about the Joolz Bekerhouder",
                    "sku": "50121",
                    "price": 29.95,
                    "attributes": [],
                    "cart_link": "/cart/?configurator=true&add-to-cart=1234&user-hash=xxx"
                },
                {
                    "identifier": "joolz-footmuff",
                    "name": "Joolz Slaapzak",
                    "description": "Something about the Joolz Slaapzak",
                    "sku": "",
                    "price": 0,
                    "attributes": [
                        {
                            "identifier": "fabric",
                            "label": "Bekleding",
                            "values": [
                                {
                                    "identifier": "parrot-blue",
                                    "label": "Parrot Blue",
                                    "default": 0,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Parrot-blue-80.png"
                                },
                                {
                                    "identifier": "hippo-grey",
                                    "label": "Hippy Grey",
                                    "default": 1,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Hippo-grey-80.png"
                                },
                                {
                                    "identifier": "nero",
                                    "label": "Nero",
                                    "default": 0,
                                    "new": 0,
                                    "image": "https://my-joolz.nl/wp-content/uploads/2013/09/Joolz-Online-Joolz-Website-Colour-Swatches-images-Nero-80.png"
                                }
                            ]
                        }
                    ],
                    "cart_link": ""
                }
                
            ]
        }